on: [push, pull_request]
name: conda build
jobs:
  build:
    name: conda build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: conda build deepmd-kit -c njzjz
    - run: conda build libdeepmd -c deepmodeling
    - run: conda build lammps-dp --use-local -c deepmodeling
